### PR TITLE
[PTCD-242] migration report fixes

### PR DESCRIPTION
**Pull request by timabell**
See the commits and their descriptions for full details.

* Fix 3 bugs in report generation
* Add basic test
* Refactor for code quality and testability.

[PTCD-242](https://skillsfundingagency.atlassian.net/browse/PTCD-242)

### CODE REVIEW

**Comment by timabell** [comment]
See also #240

**Comment by timabell** [comment]
Blocked by BA due to possible requirements change.

**Comment by timabell** [comment]
This has been okay'd to test and merge. New requirements will be in new tickets.

This PR depends on commits in `dev` so the base for this PR can't be switched to `main` until #238 is merged.

**Comment by timabell** [comment]
Changed base to `main` and rebased.

**Comment by timabell** [comment]
[release for testing](https://sfa-gov-uk.visualstudio.com/Digital%20First%20Careers/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?_a=release-pipeline-progress&releaseId=15877)

**Review by pkoppisetty — APPROVED** [review]

**Review by gunndabad — APPROVED** [review]

**Pull request merged**
